apiVersion: v1
kind: Service
metadata:
  name: druid-router
  namespace: horizen-network
  labels:
    app: druid
    component: router
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: druid
    component: router
---
apiVersion: v1
kind: Service
metadata:
  name: druid-broker
  namespace: horizen-network
  labels:
    app: druid
    component: broker
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: druid
    component: broker
---
apiVersion: v1
kind: Service
metadata:
  name: druid-coordinator
  namespace: horizen-network
  labels:
    app: druid
    component: coordinator
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: druid
    component: coordinator
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: horizen-network
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
